### ISSUE TITLE
PowerOffIntent is missing

### ISSUE THREAD

**Issue by DeMoehn** [zwrose/soundtouch_skill#1]
Hello Zach,

I've noticed that the Alexa Skill is missing a PowerOffIntent.
While skimming trough your RemoteServer code, I found a function for the PowerOffIntent.
It seems like you just forgot to add this to your Alexa Skill.

I added some SampleUtterances like:
```
PowerOffIntent Turn off the {Speaker}
PowerOffIntent stop playback on {Speaker}
PowerOffIntent stop {Speaker}
PowerOffIntent Turn off
PowerOffIntent stop
PowerOffIntent stop playback
```

I also added the PowerOffIntent to the IntentSchema.json like:
```
{
      "intent": "PowerOffIntent",
      "slots": [
        {
          "name": "Speaker",
          "type": "LIST_OF_SPEAKERS"
        }
      ]
    },
```

Soon I will add a pull request, as I also added support for german language.

**Comment by Zach-Rose-Bose** [comment]
Thanks for catching this @DeMoehn -- much appreciated! Closed as this is addressed in #2
